### PR TITLE
fix: support expansion of non-string config

### LINKED ISSUE #31: TypeError: value.matchAll is not a function
When using `numerical` values in the `application.yml` file and **restarting the application**, getting the following error

```yml
database:
  uri: some_uri
  port: 27017
```

error log
```
[Nest] 26114  - 07/18/2024, 10:46:18 PM     LOG [NestFactory] Starting Nest application...
[Nest] 26114  - 07/18/2024, 10:46:18 PM   ERROR [ExceptionHandler] value.matchAll is not a function
TypeError: value.matchAll is not a function
    at Function.lastIndexOf (/Users/my-api/node_modules/@itgorillaz/configify/src/interpolation/variables.ts:98:38)
    at Function.interpolate (/Users/my-api/node_modules/@itgorillaz/configify/src/interpolation/variables.ts:59:47)
    at Function.expand (/Users/my-api/node_modules/@itgorillaz/configify/src/interpolation/variables.ts:43:49)
    at Function.forRootAsync (/Users/my-api/node_modules/@itgorillaz/configify/src/configify.module.ts:93:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Waiting for the debugger to disconnect...
```

When i convert the number to a string like below, its working fine

```yml
database:
  uri: some_uri
  port: '27017'
```

What is the reason behind the error ` value.matchAll is not a function`

Note: You need to restart the application to get the above error while using a numerical value

### PR DESCRIPTION
**Pull request by abiriadev**
resolves #31

## Changes

```diff
- static expand(record: Record<string, any>): Record<string, any>
+ static expand(record: Record<string, unknown>): Record<string, unknown>
```

To show proper type error I replaced the `any` types with `unknown`. Now the `interpolate` method which previously accepted only `string`, will show type errors. So I changed it to handle non-string values as follows:

```diff
- private static interpolate(value: string, record: Record<string, any>): string
+ private static interpolate(value: unknown, record: Record<string, unknown>): unknown

+ if (typeof value !== 'string') return value; // this is type guard
```

I suggest changing these `unknown` to generic types (like `T`) to allow users to use their own types here.

Anyway, it will stringify any 'unknown' values during interpolating:

```diff
- value.replace(group, defaultValue || record[variableName] || ''),
+ value.replace(group, defaultValue || `${record[variableName]}` || ''),
```

This enables the interpolation of various values, including `null`, `true`, and `1234`.

```diff
- expanded[key] = this.escapeSequences(this.interpolate(value, record));
+ const interpolated = this.interpolate(value, record);
+ expanded[key] = typeof interpolated === 'string' ? this.escapeSequences(interpolated) : interpolated;
```

If the non-string value is not used during interpolation, its original value will remain.

```diff
- Object.assign(process.env, configuration);
+ const resolvedConfigs = { ...process.env, ...configuration };
```

I used `resolvedConfigs` instead of directly `Object.assign()` to `process.env`, since `process.env` converts every field to a string, or even throws a runtime error, which is not the desired behavior.

> Assigning a property on process.env will implicitly convert the value to a string. This behavior is deprecated. Future versions of Node.js may throw an error when the value is not a string, number, or boolean.

See: https://nodejs.org/docs/latest/api/process.html#processenv

## Test

Define config like this:

```ts
@Configuration()
export class TestConfig {
  @IsBoolean()
  @Value('use-https')
  https: boolean;

  @IsInt()
  @Value('port')
  port: number;
}
```

And in `application.yml`:

```yaml
use-https: true
port: 1234
```

It is parsed as (`console.log`)

```js
TestConfig { https: true, port: 1234 }
```

### CODE REVIEW

**Comment by abiriadev** [comment]
@tommelo Anyway, do you have more suggestions? 'yaml config interpolation' would require more unit tests I guess?

**Comment by tommelo** [comment]
@abiriadev thanks for this PR! Really appreciate it!

Regarding your questions:

> To show proper type error I replaced the any types with unknown. Now the interpolate method which previously accepted only string, will show type errors

Looks good!

> I suggest changing these unknown to generic types (like T) to allow users to use their own types here.

Could you provide an example of how this would look like? The config may have different types for each attribute, so I didn't see how the users would provide types for the interpolation of `Record<string, T>`.

> I used resolvedConfigs instead of directly Object.assign() to process.env, since process.env converts every field to a string, or even throws a runtime error, which is not the desired behavior.

The idea in the initial implementation for `.env` files was to actually allow users to access their config over the `process.env` as well, and as the `process.env` was converting everything to string the users should explicitly convert the values as they which using the `parse` method over their config definitions `@Value('key', { parse: (value: string) => parseInt(value) })`. Once the `yml` and `json` support were introduced this strategy became obsolete since the yml and json parsers already convert the values to its types.

I think here we should still allow the config to be assigned to `process.env` unless the user doesn't want to, so maybe introducing a new attr to the configuration may help, something like `assignToProcessEnv: boolean`. The key value pairs are already flattened so it should not be a problem to assign it if the user wants to.

> Anyway, do you have more suggestions? 'yaml config interpolation' would require more unit tests I guess?

Yes, I would suggest adding numeric and boolean fields to all the `.complex.*` files inside the `test/config` folder as well as introducing those attributes to the `complex-*.configuration.ts` files in the same folder.

So maybe we could think about first fixing the issue by just performing a null check to the value and then passing the value as string to be interpolated `value.toString()` and then we could create another PR including the improvements on `process.env` assignment, `unknown` types and so on.

What do you think?

**Comment by abiriadev** [comment]
> @abiriadev thanks for this PR! Really appreciate it!

I'm glad that you appreciate it!

>> I suggest changing these unknown to generic types (like T) to allow users to use their own types here.
> 
> Could you provide an example of how this would look like? The config may have different types for each attribute, so I didn't see how the users would provide types for the interpolation of `Record<string, T>`.

I see your point. Initially, I misunderstood. Since `@Configuration()` will be the single source of truth, users won’t need to provide additional types. So, using `unknown` seems appropriate here.

>> I used resolvedConfigs instead of directly Object.assign() to process.env, since process.env converts every field to a string, or even throws a runtime error, which is not the desired behavior.
> 
> The idea in the initial implementation for `.env` files was to actually allow users to access their config over the `process.env` as well, and as the `process.env` was converting everything to string the users should explicitly convert the values as they wish using the `parse` method over their config definitions `@Value('key', { parse: (value: string) => parseInt(value) })`. Once the `yml` and `json` support were introduced this strategy became obsolete since the yml and json parsers already convert the values to its types.
> 
> I think here we should still allow the config to be assigned to `process.env` unless the user doesn't want to, so maybe introducing a new attr to the configuration may help, something like `assignToProcessEnv: boolean`. The key value pairs are already flattened so it should not be a problem to assign it if the user wants to.

Thanks for the clarification! I initially thought `configify` would avoid manual parsing, but now I understand that using `@Value({ parse })` is the intended approach. I’ll revert that change :)

>> Anyway, do you have more suggestions? 'yaml config interpolation' would require more unit tests I guess?
> 
> Yes, I would suggest adding numeric and boolean fields to all the `.complex.*` files inside the `test/config` folder as well as introducing those attributes to the `complex-*.configuration.ts` files in the same folder.

Got it! I'll add those tests.

> So maybe we could think about first fixing the issue by just performing a null check to the value and then passing the value as string to be interpolated `value.toString()`

It has already been addressed by:

> Anyway, it will stringify any 'unknown' values during interpolating:
> 
> ```diff
> - value.replace(group, defaultValue || record[variableName] || ''),
> + value.replace(group, defaultValue || `${record[variableName]}` || ''),
> ```

> and then we could create another PR including the improvements on `process.env` assignment, `unknown` types and so on.
> 
> What do you think?

That sounds great to me!

**Comment by abiriadev** [comment]
Seems all tests passing!

```sh
Test Suites: 9 passed, 9 total
Tests:       19 passed, 19 total
Snapshots:   0 total
Time:        4.025 s
Ran all test suites.
```

**Review by tommelo — APPROVED** [review]

**Pull request merged**
